# Generated by Django 5.0 on 2023-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB1', 'Running Back 1'), ('RB2', 'Running Back 2'), ('WR1', 'Wide Receiver 1'), ('WR2', 'Wide Receiver 2'), ('TE', 'Tight End'), ('FLEX1', 'Flex 1'), ('FLEX2', 'Flex 2'), ('FLEX3', 'Flex 3'), ('SCALED_FLEX', 'Scaled Flex'), ('K', 'Kicker'), ('D/ST', 'Defense/Special Teams')], max_length=12)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
