# Generated by Django 4.2.9 on 2024-12-17 17:58

import computedfields.resolver
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('wild_card_score', models.FloatField(default=0.0)),
                ('divisional_score', models.FloatField(default=0.0)),
                ('conference_score', models.FloatField(default=0.0)),
                ('super_bowl_score', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('DEF', 'Defense/Special Teams')], max_length=12)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RosteredPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_scaled_flex', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.entry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.player')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='players',
            field=models.ManyToManyField(through='fantasy_football_app.RosteredPlayers', to='fantasy_football_app.player'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, choices=[('WC', 'Wild Card'), ('DIV', 'Divisional'), ('CONF', 'Conference'), ('SB', 'Super Bowl')], max_length=12, null=True)),
                ('passing_yards', models.IntegerField(default=0)),
                ('passing_tds', models.IntegerField(default=0)),
                ('passing_interceptions', models.IntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('receiving_tds', models.IntegerField(default=0)),
                ('fumbles_lost', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fumbles_recovered', models.IntegerField(default=0)),
                ('safeties', models.IntegerField(default=0)),
                ('defensive_tds', models.IntegerField(default=0)),
                ('return_tds', models.IntegerField(default=0)),
                ('points_allowed', models.IntegerField(default=0)),
                ('two_pt_conversions', models.IntegerField(default=0)),
                ('week_score', models.FloatField(editable=False)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.player')),
            ],
            options={
                'unique_together': {('player', 'week')},
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
