# Generated by Django 5.0 on 2023-12-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0003_entry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker'), ('D/ST', 'Defense/Special Teams')], max_length=12)),
                ('passing_yards', models.IntegerField(default=0)),
                ('passing_tds', models.IntegerField(default=0)),
                ('passing_interceptions', models.IntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('fumbles_lost', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('safeties', models.IntegerField(default=0)),
                ('defensive_tds', models.IntegerField(default=0)),
                ('return_tds', models.IntegerField(default=0)),
                ('wild_card_score', models.IntegerField(default=0)),
                ('divisional_score', models.IntegerField(default=0)),
                ('conference_score', models.IntegerField(default=0)),
                ('super_bowl_score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.entry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.player')),
            ],
            options={
                'unique_together': {('player', 'entry')},
            },
        ),
    ]
