# Generated by Django 5.0 on 2023-12-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0006_weeklystats_remove_playerstats_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='blocks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='defensive_tds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='fumbles_lost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='interceptions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_interceptions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_tds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_yards',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='receptions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='return_tds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='rushing_tds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='rushing_yards',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='sacks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='safeties',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='week_score',
            field=models.FloatField(default=0),
        ),
    ]
