# Generated by Django 5.0 on 2023-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0007_alter_playerstats_total_alter_weeklystats_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='receiving_tds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='receiving_yards',
            field=models.FloatField(default=0),
        ),
    ]
