# Generated by Django 5.0 on 2023-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0008_weeklystats_receiving_tds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='points_allowed',
            field=models.FloatField(default=0),
        ),
    ]
