# Generated by Django 5.0 on 2023-12-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0009_weeklystats_points_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='conference_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='divisional_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='super_bowl_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='wild_card_score',
            field=models.FloatField(default=0.0),
        ),
    ]
