# Generated by Django 5.0 on 2024-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0010_entry_conference_score_entry_divisional_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=255)),
                ('entry_score', models.FloatField()),
                ('standings_place', models.IntegerField()),
            ],
        ),
    ]
