# Generated by Django 4.2.9 on 2024-01-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0012_alter_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosteredPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_id', models.IntegerField(default=0)),
                ('is_captain', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.entry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.player')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='players',
        ),
        migrations.AddField(
            model_name='entry',
            name='players',
            field=models.ManyToManyField(through='fantasy_football_app.RosteredPlayers', to='fantasy_football_app.player'),
        ),
    ]
