# Generated by Django 4.2.9 on 2024-01-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0015_remove_rosteredplayers_roster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='position',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='team',
        ),
    ]
