# Generated by Django 4.2.9 on 2024-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0016_remove_playerstats_entry_remove_playerstats_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklystats',
            name='blocks',
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='fumbles_recovered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='two_pt_conversions',
            field=models.FloatField(default=0),
        ),
    ]
