# Generated by Django 4.2.9 on 2024-01-10 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0017_remove_weeklystats_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy_football_app.player'),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='week',
            field=models.CharField(blank=True, choices=[('WC', 'Wild Card'), ('DIV', 'Divisional'), ('CONF', 'Conference'), ('SB', 'Super Bowl')], max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
