# Generated by Django 4.2.9 on 2024-01-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0018_weeklystats_player_weeklystats_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystats',
            name='defensive_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='fumbles_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='fumbles_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='passing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='points_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='receiving_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='return_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='rushing_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='rushing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='safeties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='two_pt_conversions',
            field=models.IntegerField(default=0),
        ),
    ]
