# Generated by Django 4.2.9 on 2024-01-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0019_alter_weeklystats_defensive_tds_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklystats',
            unique_together={('player', 'week')},
        ),
    ]
