# Generated by Django 4.2.9 on 2024-01-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0020_alter_weeklystats_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklystats',
            name='week_score',
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='week_score',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
