# Generated by Django 4.2.9 on 2024-01-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0016_rosteredplayers_is_scaled_flex'),
        ('fantasy_football_app', '0021_weeklystats_week_score_computed'),
    ]

    operations = [
    ]
