# Generated by Django 4.2.9 on 2024-01-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0022_merge_20240111_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standings',
        ),
    ]
