# Generated by Django 4.2.9 on 2024-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0024_csvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='week',
            field=models.CharField(choices=[('WC', 'Wild Card'), ('DIV', 'Divisional'), ('CONF', 'Conference'), ('SB', 'Super Bowl')], default='WC', max_length=12),
        ),
    ]
