# Generated by Django 4.2.9 on 2024-12-24 05:12

from django.db import migrations, models
import fantasy_football_app.constants


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0025_csvupload_name_alter_csvupload_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.AddField(
            model_name='rosteredplayers',
            name='roster_position',
            field=models.CharField(choices=[(fantasy_football_app.constants.RosterPositions['QB'], 'QB'), (fantasy_football_app.constants.RosterPositions['RB1'], 'RB1'), (fantasy_football_app.constants.RosterPositions['RB2'], 'RB2'), (fantasy_football_app.constants.RosterPositions['WR1'], 'WR1'), (fantasy_football_app.constants.RosterPositions['WR2'], 'WR2'), (fantasy_football_app.constants.RosterPositions['TE'], 'TE'), (fantasy_football_app.constants.RosterPositions['Flex1'], 'Flex1'), (fantasy_football_app.constants.RosterPositions['Flex2'], 'Flex2'), (fantasy_football_app.constants.RosterPositions['Flex3'], 'Flex3'), (fantasy_football_app.constants.RosterPositions['Flex4'], 'Flex4'), (fantasy_football_app.constants.RosterPositions['ScaledFlex'], 'Scaled Flex'), (fantasy_football_app.constants.RosterPositions['DEF'], 'DEF'), (fantasy_football_app.constants.RosterPositions['K'], 'K'), (fantasy_football_app.constants.RosterPositions['NA'], '')], default=fantasy_football_app.constants.RosterPositions['NA'], max_length=20),
        ),
    ]
