# Generated by Django 4.2.9 on 2024-12-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0025_csvupload_name_alter_csvupload_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.AddField(
            model_name='rosteredplayers',
            name='roster_position',
            field=models.CharField(choices=[('QB', 'QB'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('TE', 'TE'), ('Flex1', 'Flex1'), ('Flex2', 'Flex2'), ('Flex3', 'Flex3'), ('Flex4', 'Flex4'), ('Scaled Flex', 'Scaled Flex'), ('DEF', 'DEF'), ('K', 'K')], default='', max_length=20),
        ),
    ]
