# Generated by Django 4.2.9 on 2024-12-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0026_delete_csvupload_rosteredplayers_roster_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025')], default='2024', max_length=12),
        ),
    ]
