# Generated by Django 4.2.9 on 2024-12-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0028_playerstats_playerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
