# Generated by Django 4.2.9 on 2024-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0029_playerinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('DEF', 'Defense/Special Teams'), ('K', 'Kicker')], max_length=12),
        ),
    ]
