# Generated by Django 4.2.9 on 2025-01-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0030_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosteredplayers',
            name='roster_position',
            field=models.CharField(choices=[('QB', 'QB'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('TE', 'TE'), ('Flex1', 'Flex1'), ('Flex2', 'Flex2'), ('Scaled Flex1', 'Scaled Flex1'), ('Scaled Flex2', 'Scaled Flex2'), ('DEF', 'DEF'), ('K', 'K')], default='', max_length=20),
        ),
    ]
