# Generated by Django 4.2.9 on 2025-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0032_remove_playerstats_sacked_playerstats_def_td_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
