# Generated by Django 4.2.9 on 2025-01-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0033_playerstats_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='fg_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='fg_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='xp_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='xp_missed',
            field=models.IntegerField(default=0),
        ),
    ]
