# Generated by Django 4.2.9 on 2025-01-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0034_weeklystats_fg_made_weeklystats_fg_missed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklystats',
            name='kicks_blocked',
            field=models.IntegerField(default=0),
        ),
    ]
