# Generated by Django 4.2.9 on 2026-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0035_weeklystats_kicks_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2026', max_length=12),
        ),
    ]
