# Generated by Django 4.2.9 on 2026-01-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0036_alter_entry_year'),
    ]

    operations = [
        # NOTE: older databases may not have the previous (player, week) unique constraint; avoid trying
        # to drop it explicitly to prevent failures when it is missing. We add the new `season` field and
        # then create the new unique_together including `season`.
        migrations.AddField(
            model_name='weeklystats',
            name='season',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2025', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='weeklystats',
            unique_together={('player', 'week', 'season')},
        ),
    ]
