# Generated by Django 4.2.9 on 2026-01-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_app', '0037_alter_weeklystats_unique_together_weeklystats_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystats',
            name='season',
            field=models.CharField(default='2025', max_length=12),
        ),
    ]
